### ISSUE TITLE
LICENSE.md file

### ISSUE THREAD

**Issue by bluquark** [samanbarghi/CPP2C#2]
I'm an engineer on Google's Android team planning to write a tool to generate C APIs for some C++ libraries we are using in the Android NDK.  I found out about CPP2C and I'm interested in using it as a starting point.  But by company policy, I can't use any code without a specific open-source license, and this particular repository doesn't have one.

Would you mind committing a LICENSE.md file into the repository?  The Apache 2.0 license, like the one used in https://github.com/samanbarghi/wrap-syscall would be ideal.

Thanks a lot!

**Comment by samanbarghi** [comment]
Done. Hope it helps.

**Comment by bluquark** [comment]
Thanks for the quick response, much appreciated!
